```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup', fig.width = 12, fig.height = 7, fig.align = "center")
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here
Sys.setlocale(category = "LC_ALL", locale = "en_US.utf8")
# end setup chunk
```

```{r readdata1, echo = FALSE}
bmw_2014 <- readRDS("BMW2014.rds")
```

# legend()

For a more readable graphic we also add a legend to our graph.

```{r ohlcbaselegend}
# Creating base plot

plot(x = bmw_2014[,"Date"], y = bmw_2014[,"Close"], 
     type = "l", xlab = "", ylab = "",
     main = "OHLC Prices BMW 2014", ylim = c(70,100))

# adding lines to the existing plot device

lines(x = bmw_2014[,"Date"], y = bmw_2014[,"Open"],
      col = "green", lty = "dotted")
lines(x = bmw_2014[,"Date"], y = bmw_2014[,"High"],
      col = "red", lty = "dotdash")
lines(x = bmw_2014[,"Date"], y = bmw_2014[,"Low"],
      col = "blue", lty = "longdash")

# adding a legend

legend("bottom", # position of the legend
       legend = c("Open", "High", "Low", "Close"), # displayed names
       col = c("green", "red", "blue", "black"), # displayed colors
       lty = c("dotted", "dotdash", "longdash", "solid")) # displayed linetypes
```