# Solutions

```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md', fig.align = "center")
opts_chunk$set(prompt=TRUE, comment='', results='markup', fig.width = 12, fig.height = 7, fig.align = "center")
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here
library(Quandl)
Quandl.auth("x81naq-zMUpwM9fzkhYq")
Sys.setlocale(category = "LC_ALL", locale = "en_US.utf8")
library(fGarch)
# births <- Quandl("INSEE/62_001641602_M", type = "ts")
# end setup chunk
```

```{r}
# Solution Exercise 1
Quandl.search("S&P 500", source = "YAHOO")
sp500 <- Quandl("YAHOO/INDEX_GSPC.4",
                start_date = "2010-01-01", end_date = "2014-01-01",
                sort = "asc")

close_prices <- sp500[,"Close"]

# Solution Exercise 2
plot(close_prices, type = "l") # Random Walk (with drift)
plot(log(close_prices), type = "l") # Random Walk (with drift)
log_returns <- diff(log(close_prices))
plot(log_returns, type = "l")
acf(log_returns)
acf(log_returns^2)

# Solution Exercise 3
garch_fit <- garchFit(formula = ~ garch(1,1), data = log_returns,
                      include.mean = FALSE, trace = FALSE)
garch_fit_std <- garchFit(formula = ~ garch(1,1), data = log_returns,
                          cond.dist = "std", include.mean = FALSE, trace = FALSE)

# The model with lower AIC, BIC, ...


# Solution Exercise 4
vola_forecast <- function(fit, n.ahead=1, cond.dist = c("norm", "std")) {
  # fit is an object of class "fGarch"
  vola <- numeric(n.ahead + 1)
  coefs <- coef(fit)
  h_init <- fit@h.t[length(fit@h.t)] # last value of fitted sigma^2
  eps <- fit@residuals[length(fit@residuals)]  # last value of eps_t
  
  h <- coefs["omega"] + coefs["alpha1"] * eps^2 +
       coefs["beta1"] * h_init # one-step ahead forecast
  
  if(n.ahead == 1) {
    res <- h
    names(res) <- NULL
    return(sqrt(res))
  } else {
    vola_part1 <- coefs["omega"] *
                  (1 - (coefs["alpha1"] + coefs["beta1"])^(1:(n.ahead-1)))/
                  (1 - (coefs["alpha1"] + coefs["beta1"]))
    
    vola_part2 <- (coefs["alpha1"] + coefs["beta1"])^(1:(n.ahead-1)) * h
  
    vola <- vola_part1 + vola_part2
    res <- c(h,vola)
    names(res) <- NULL
    return(sqrt(res))
  }
}
```