```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup', fig.width = 12, fig.height = 7, fig.align = "center")
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here
Sys.setlocale(category = "LC_ALL", locale = "en_US.utf8")
# end setup chunk
```

# Solutions

```{r sol1,bootstrap.show.output = TRUE}
# Solution Exercise 1:
set.seed(111)
wn <- rnorm(500, mean = 0, sd = 1)
rw_wo_drift <- cumsum(wn)
plot(rw_wo_drift, type = "l", lty = "dashed", col = "red")
```

```{r sol2, bootstrap.show.output = TRUE}
# Solution Exercise 2:
wn_drift <- rnorm(500, mean = 0, sd = 1)
rw_drift <- cumsum(wn_drift + 0.2)

plot(rw_drift, type = "l", lty = "dashed", col = "cyan", ylim = c(-20,125))
lines(rw_wo_drift, lty = "dotted", col = "orange")
legend("topleft", 
       legend = c("Random Walk with drift", "Random Walk without Drift"),
       col = c("cyan", "orange"),
       lty = c("dashed", "dotted"))
```

```{r sol3, bootstrap.show.output = TRUE}
# Solution Exercise 3:

Box.test(rw_wo_drift, type = "Box-Pierce")
Box.test(rw_wo_drift, type = "Ljung-Box")

Box.test(rw_drift, type = "Box-Pierce")
Box.test(rw_drift, type = "Ljung-Box")

Box.test(diff(rw_wo_drift), type = "Box-Pierce")
Box.test(diff(rw_wo_drift), type = "Ljung-Box")

# White Noise
```